<robot name="camera"
  xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:property name="camera_length" value="0.01" />
  <xacro:property name="camera_width" value="0.025" />
  <xacro:property name="camera_height" value="0.025" />
  <xacro:property name="camera_x" value="0.02" />
  <xacro:property name="camera_y" value="0.0" />
  <xacro:property name="camera_z" value="${laser_length / 2 + camera_height / 2}" />

  <link name="camera">
    <visual>
      <geometry>
        <box size="${camera_length} ${camera_width} ${camera_height}" />
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <material name="black" />
    </visual>
  </link>

  <joint name="camera2laser" type="fixed">
    <parent link="laser" />
    <child link="camera" />
    <origin xyz="${camera_x} ${camera_y} ${camera_z}" />
  </joint>
</robot>
