<robot name="diff_move"
  xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="joint_trans" params="joint_name">
    <transmission name="${joint_name}_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${joint_name}">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
      </joint>
      <actuator name="${joint_name}_motor">
        <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
  </xacro:macro>
  <xacro:joint_trans joint_name="left_wheel2base_link" />
  <xacro:joint_trans joint_name="right_wheel2base_link" />

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <updateRate>100.0</updateRate>
      <leftJoint>left_wheel2base_link</leftJoint>
      <rightJoint>right_wheel2base_link</rightJoint>
      <wheelSeparation>${base_link_radius * 2}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <wheelTorque>30</wheelTorque>
      <wheelAcceleration>1.8</wheelAcceleration>
      <commandTopic>/cmd_vel</commandTopic>
      <odometryFrame>odom</odometryFrame>
      <odometryTopic>/odom</odometryTopic>
      <robotBaseFrame>base_footprint</robotBaseFrame>
      <!-- Set to true to swap right and left wheels, defaults to true -->
      <legacyMode>false</legacyMode>
      <!-- avoid clash with rviz, robot_state_publisher & joint_state_publisher -->
      <!-- Set to true to publish transforms for the wheel links, defaults to false -->
      <publishWheelTF>false</publishWheelTF> 
      <!-- Set to true to publish sensor_msgs/JointState on /joint_states for the wheel joints, defaults to false -->
      <publishWheelJointState>false</publishWheelJointState>
      <!-- Set to true to publish transforms for the odometry, defaults to true -->
      <publishOdom>true</publishOdom>
    </plugin>
  </gazebo>

</robot>
