# Joystick axis to use for linear movement control.  
axis_linear: 7  
# Scale to apply to joystick linear axis for regular-speed movement, in m/s.
scale_linear: 1.0 
# Scale to apply to joystick linear axis for high-speed movement, in m/s.
scale_linear_turbo: 1.2 

# Joystick axis to use for angular movement control.
axis_angular: 6
# Scale to apply to joystick linear axis for regular-speed movement, in m/s.
scale_angular: 1.0 
# Scale to apply to joystick angular axis for high-speed movement, in rad/s.
scale_angular_turbo: 1.2 

enable_button: 6 # regular-speed
enable_turbo_button: 8 # high-speed